### ISSUE TITLE
How will opencache store data?

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/opencache#8]
Do we just store data in memory? Or do we store data in persistent storage like local fs?

**Comment by drmingdrmer** [comment]
Most data on disk. Otherwise, a MemoryCache cluster would be better.

The hottest data will be cached in memory unless the access pattern has a very low data locality. I.e., `p` is small in a [zipf](https://en.wikipedia.org/wiki/Zipf%27s_law) distribution.

$$
f(k;\rho )\approx {\frac {[{\text{constant}}]}{k^{\rho +1}}}
$$
